#!/usr/bin/env python3
"""
MPI Network Configuration Module

Automatically configures OpenMPI network settings to avoid interface conflicts
by reading cluster IPs from configuration and setting up proper MCA parameters.

This solves the "Unable to find reachable pairing between local and remote interfaces"
error by ensuring OpenMPI only uses the designated cluster IPs and ignores:
- Docker bridges (172.17.0.0/16)
- libvirt networks (192.168.122.0/24)
- WSL virtual interfaces (10.x.x.x)
- Secondary physical IPs
"""

import subprocess
import yaml
from pathlib import Path
from typing import List, Dict, Optional
from dataclasses import dataclass


@dataclass
class NetworkConfig:
    """Network configuration for MPI"""
    cluster_ips: List[str]
    subnet: str
    exclude_networks: List[str]
    btl_port_min: int = 50000
    oob_port_range: str = "50100-50200"
    openmpi_prefix: str = "/home/linuxbrew/.linuxbrew/Cellar/open-mpi/5.0.8"
    opal_prefix: str = "/home/linuxbrew/.linuxbrew"


class MPINetworkConfigurator:
    """Configure MPI network settings across cluster"""
    
    def __init__(self, config_file: str = "cluster_config_actual.yaml"):
        self.config_file = Path(config_file)
        self.network_config = self._load_config()
    
    def _load_config(self) -> NetworkConfig:
        """Load cluster configuration and extract network settings"""
        if not self.config_file.exists():
            raise FileNotFoundError(f"Config file not found: {self.config_file}")
        
        with open(self.config_file) as f:
            config = yaml.safe_load(f)
        
        # Extract IPs from config
        cluster_ips = [config['master']['ip']]
        for worker in config.get('workers', []):
            cluster_ips.append(worker['ip'])
        
        # Determine subnet (assume all IPs in same /24)
        # Example: 192.168.1.147 -> 192.168.1.0/24
        base_ip = cluster_ips[0]
        subnet_parts = base_ip.split('.')
        subnet = f"{subnet_parts[0]}.{subnet_parts[1]}.{subnet_parts[2]}.0/24"
        
        # Networks to exclude (virtual interfaces)
        exclude_networks = [
            "172.16.0.0/12",   # Docker default
            "10.0.0.0/8",       # Private network / WSL
            "192.168.122.0/24", # libvirt default
        ]
        
        return NetworkConfig(
            cluster_ips=cluster_ips,
            subnet=subnet,
            exclude_networks=exclude_networks
        )
    
    def generate_mca_config(self) -> str:
        """Generate OpenMPI MCA configuration content"""
        config_lines = [
            "# OpenMPI MCA parameters - Auto-generated by mpi_network_config.py",
            "# This configuration ensures MPI only uses designated cluster IPs",
            "",
            "# Disable InfiniBand (not available in this cluster)",
            "btl = ^openib",
            "",
            f"# Use subnet containing cluster IPs: {', '.join(self.network_config.cluster_ips)}",
            f"btl_tcp_if_include = {self.network_config.subnet}",
            f"oob_tcp_if_include = {self.network_config.subnet}",
            "",
            "# OpenMPI installation prefix - critical for finding prted on remote nodes",
            f"orte_prefix = {self.network_config.openmpi_prefix}",
            f"opal_prefix = {self.network_config.opal_prefix}",
            "",
            "# Port configuration for firewall-friendly operation",
            f"btl_tcp_port_min_v4 = {self.network_config.btl_port_min}",
            f"oob_tcp_port_range = {self.network_config.oob_port_range}",
            "",
            "# Additional troubleshooting options (uncomment if needed)",
            "# btl_base_verbose = 10",
            "# oob_base_verbose = 10",
        ]
        
        return "\n".join(config_lines)
    
    def get_interface_for_ip(self, node_ip: str, target_ip: str) -> Optional[str]:
        """Get network interface name for a specific IP on a remote node"""
        try:
            cmd = f"ssh {node_ip} \"ip addr show | grep -B 2 '{target_ip}/' | grep 'mtu' | awk '{{print $2}}' | sed 's/:$//'\""
            result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=10)
            if result.returncode == 0 and result.stdout.strip():
                return result.stdout.strip()
        except Exception as e:
            print(f"Warning: Could not determine interface for {target_ip} on {node_ip}: {e}")
        return None
    
    def get_primary_interface_per_node(self) -> Dict[str, str]:
        """
        Determine which network interface each node should use.
        Returns dict of {node_ip: interface_name}
        """
        interfaces = {}
        for ip in self.network_config.cluster_ips:
            interface = self.get_interface_for_ip(ip, ip)
            if interface:
                interfaces[ip] = interface
                print(f"  {ip}: {interface}")
            else:
                print(f"  {ip}: Could not determine interface (will rely on subnet config)")
        
        return interfaces
    
    def deploy_config(self, nodes: Optional[List[str]] = None):
        """
        Deploy MCA configuration to all cluster nodes
        
        Args:
            nodes: List of node IPs to configure. If None, uses all from config.
        """
        if nodes is None:
            nodes = self.network_config.cluster_ips
        
        # Generate configuration
        mca_config = self.generate_mca_config()
        
        # Write to temporary file
        temp_file = Path("/tmp/mca-params.conf")
        temp_file.write_text(mca_config)
        
        print(f"\nGenerated MCA configuration:")
        print("=" * 60)
        print(mca_config)
        print("=" * 60)
        
        # Deploy to each node
        print(f"\nDeploying to {len(nodes)} nodes...")
        for node_ip in nodes:
            try:
                # Create .openmpi directory
                subprocess.run(
                    f"ssh {node_ip} 'mkdir -p ~/.openmpi'",
                    shell=True,
                    check=True,
                    timeout=10
                )
                
                # Backup existing config
                subprocess.run(
                    f"ssh {node_ip} 'cp ~/.openmpi/mca-params.conf ~/.openmpi/mca-params.conf.backup 2>/dev/null || true'",
                    shell=True,
                    timeout=10
                )
                
                # Copy new config
                subprocess.run(
                    f"scp {temp_file} {node_ip}:~/.openmpi/mca-params.conf",
                    shell=True,
                    check=True,
                    timeout=15
                )
                
                print(f"  ✓ {node_ip}")
                
            except subprocess.TimeoutExpired:
                print(f"  ✗ {node_ip} - timeout")
            except subprocess.CalledProcessError as e:
                print(f"  ✗ {node_ip} - error: {e}")
        
        print("\nConfiguration deployed successfully!")
        print(f"Backup saved as: ~/.openmpi/mca-params.conf.backup")
    
    def verify_deployment(self, nodes: Optional[List[str]] = None) -> bool:
        """
        Verify MCA configuration is properly deployed on all nodes
        
        Returns:
            True if all nodes have correct configuration
        """
        if nodes is None:
            nodes = self.network_config.cluster_ips
        
        print(f"\nVerifying configuration on {len(nodes)} nodes...")
        all_ok = True
        
        for node_ip in nodes:
            try:
                result = subprocess.run(
                    f"ssh {node_ip} 'grep btl_tcp_if_include ~/.openmpi/mca-params.conf'",
                    shell=True,
                    capture_output=True,
                    text=True,
                    timeout=10
                )
                
                if result.returncode == 0:
                    value = result.stdout.strip()
                    if self.network_config.subnet in value:
                        print(f"  ✓ {node_ip}: {value}")
                    else:
                        print(f"  ✗ {node_ip}: Unexpected value: {value}")
                        all_ok = False
                else:
                    print(f"  ✗ {node_ip}: Config file not found or not readable")
                    all_ok = False
                    
            except Exception as e:
                print(f"  ✗ {node_ip}: Error: {e}")
                all_ok = False
        
        return all_ok
    
    def print_summary(self):
        """Print configuration summary"""
        print("\n" + "=" * 60)
        print("MPI Network Configuration Summary")
        print("=" * 60)
        print(f"Cluster IPs: {', '.join(self.network_config.cluster_ips)}")
        print(f"Subnet: {self.network_config.subnet}")
        print(f"BTL Port: {self.network_config.btl_port_min}")
        print(f"OOB Ports: {self.network_config.oob_port_range}")
        print("=" * 60)


def main():
    """Main entry point for CLI usage"""
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Configure OpenMPI network settings for cluster"
    )
    parser.add_argument(
        "--config",
        default="cluster_config_actual.yaml",
        help="Path to cluster configuration file"
    )
    parser.add_argument(
        "--deploy",
        action="store_true",
        help="Deploy configuration to all nodes"
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Verify configuration on all nodes"
    )
    parser.add_argument(
        "--show-interfaces",
        action="store_true",
        help="Show primary network interface for each node"
    )
    
    args = parser.parse_args()
    
    # Initialize configurator
    configurator = MPINetworkConfigurator(args.config)
    configurator.print_summary()
    
    if args.show_interfaces:
        print("\nDetecting primary network interfaces...")
        configurator.get_primary_interface_per_node()
    
    if args.deploy:
        configurator.deploy_config()
        
        # Auto-verify after deployment
        if configurator.verify_deployment():
            print("\n✓ All nodes configured correctly!")
        else:
            print("\n✗ Some nodes have configuration issues. Please check manually.")
    
    elif args.verify:
        if configurator.verify_deployment():
            print("\n✓ All nodes configured correctly!")
        else:
            print("\n✗ Some nodes have configuration issues.")
    
    else:
        # Just print the config without deploying
        print("\nGenerated MCA Configuration:")
        print("=" * 60)
        print(configurator.generate_mca_config())
        print("=" * 60)
        print("\nTo deploy, run with --deploy flag")


if __name__ == "__main__":
    main()
